ログイン機能の実装
yanbaru-expert/team_project_39 pull request #21
Opened 2020-12-28 14:58 UTC by kawakami-masachika

## #8

close #8

## 実装内容

- ログイン機能
  - ログイン用gem `devise`の導入
  - ユーザーモデルの作成
  - 共通のヘッダに、ログイン/ログアウト/新規登録のリンクを追加
  - テストデータ作成のためのロジックを追加
  - 各アクション時にログインの必須化

## 参考資料

- ログイン機能
  - [やんばるCODEアプリ](https://arcane-gorge-21903.herokuapp.com/texts/219)
  -  [デバイスを導入してみる](https://qiita.com/Hal_mai/items/350c400e8763ce0487a3)
  - [before_action :authenticate_user!をコントローラごとに書かない方法](https://qiita.com/ryuuuuuuuuuu/items/bf7e2ea18ef29254b3dd)

## チェックリスト
- [ ] 新規登録の動作確認
- [ ] ログインの動作確認
- [ ] ログアウトの動作確認
- [ ] ログイン必須の動作確認
- [ ] GitHub で Files changed を確認
- [ ] 影響し得る範囲のローカル環境での動作確認

## 備考（必要があれば）
各自ローカルに変更を取り込んだ後、以下のコマンドを実行して動作確認を行って下さい。

1. `bundle install`
2. `rails db:seed` ⇛ テストデータの導入
3. `rails s`でサーバー起動
4. ログイン
5. ログアウト
6. 新規登録
7. ログアウトした状態で `http://localhost:3000/`にアクセスすると、ログインページに遷移すること

2020-12-28 22:15 UTC, T-Tsujii requested changes

2020-12-28 22:15 UTC, T-Tsujii commented on app/views/layouts/application.html.erb
> +        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
好みの問題もありますが，「操作ミスでログアウト」してしまわないようにするために，アラートを出してもよいですね。

ここに属性を追加するだけで対応できます。

2020-12-28 22:15 UTC, T-Tsujii commented on db/seeds.rb
>  #   Character.create(name: 'Luke', movie: movies.first)
ここのコメントは必要ないので削除していただけますか。

2020-12-29 01:12 UTC, T-Tsujii approved these changes
LGTMです！

2020-12-29 01:12 UTC, merged

2020-12-29 07:06 UTC, koganeyumi commented
ターミナルでrails db:seedを行ったら、結果が下記のように出ました。
これは、rails db:migrateして大丈夫ですか？？
You have 3 pending migrations:
  20201228104715 CreateTexts
  20201228105220 CreateMovies
  20201228135656 DeviseCreateUsers
Run `rails db:migrate` to update your database then try again.